Fix unknown error type in span tag rpc.tchannel.system_error_code
uber/tchannel-go pull request #907
Opened 2023-11-15 09:46 UTC by deepanshumehndiratta

This change fixes the issue with an unknown error type being tagged in the tracing span for system errors. It also abstracts out setting the span tag to a different method which is called for both system and application errors

2023-11-21 00:43 UTC, cinchurge requested changes
the change looks ok, but can please add an end-to-end test? probably follow something like TestThriftTracingPropagation

2023-11-29 04:11 UTC, deepanshumehndiratta commented
> the change looks ok, but can please add an end-to-end test? probably follow something like TestThriftTracingPropagation

Addressed with e2e tests

2023-11-29 22:18 UTC, cinchurge commented on inbound_test.go
> +		// We use a jaeger tracer here and not Mocktracer: because jaeger supports
use `t.Run(...` here so the results for each test case can be reported separately (also allows the defers to be run per test instead of stacking them in a loop, which is an antipattern)

2023-11-29 22:18 UTC, cinchurge commented on inbound_test.go
> +			}
it looks like you don't plan to modify the frame. i don't think a relay is necessary here? you should be able to send the request directly to the test server

2023-11-29 22:18 UTC, cinchurge commented on inbound_test.go
> +				// failed test ouput would otherwise print out hex codes.
```suggestion
				// failed test output would otherwise print out hex codes.
```

2023-12-04 17:25 UTC, cinchurge approved these changes

2023-12-05 05:37 UTC, merged